version: "3"

services:
  nginx:
    container_name: "nginx_master"
    hostname: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./conf/*:/etc/nginx/conf.d/*
    networks:
      - internal
      - public

networks:
  internal: {}
  public:
    external: true
